### ISSUE TITLE
Docker Containerization

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/backend-m2m#2]
[Docker](https://www.docker.com/) is an amazing tool used to configure and deploy services on the cloud. We will be using it to make our development and deployment pipeline extremely easy and reproducible. 

You will be writing a Dockerfile to package Rabbit, Gateway and Processing Service into individual docker containers, and a docker-compose file so that the repo can be pulled by any server and used to spin up our microservices on those services. [This guide](https://docker-curriculum.com/) will be really helpful in understanding and implementing the file. 

Requirements: 
- [ ] Dockerfile for both microservices 
- [ ] docker-compose.yml which runs both microservices, and a rabbitmq image from Dockerhub. 
- [ ] Pass relevant environment variables (ask @r614 ) 
You can work with #9 #1 to create the CI/CD Pipeline.

**Comment by r614** [comment]
@mattmajo i edited the issue a bit, feel free to ping me if you run into any problems!
